# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 14:37
from __future__ import unicode_literals

from django.db import migrations, models

def populate_handicaps_and_wins(apps, schema_editor):
    from pool.league.models import Match
    for match in Match.objects.all():
        match.calculate_handicaps()
        summary = match.summary()
        match.points1 = summary['points1']
        match.points2 = summary['points2']
        match.save()

class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='handicap1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='handicap2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='points1',
            field=models.DecimalField(max_digits=3, decimal_places=1, default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='points2',
            field=models.DecimalField(max_digits=3, decimal_places=1, default=0),
        ),
        migrations.RunPython(populate_handicaps_and_wins)
    ]
